---
version: 2
updates:
  - package-ecosystem: bundler
    directory: /docker-action
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: build(deps)
