version = 1

[approve]
auto_approve_usernames = ["dependabot"]

[merge.automerge_dependencies]
versions = ["major", "minor", "patch"]
usernames = ["dependabot"]

[merge.message]
title = "pull_request_title"
