# action.yml
# See
# https://help.github.com/en/actions/building-actions/creating-a-docker-container-action

name: 'LINZ Debian Packaging'
description: 'Build Debian packages for LINZ software repository'
inputs:
  repo:
    description: 'Path to source repository of project to build packages of'
    required: false
    default: '/github/workspace'
  packagecloud_token:
    description: 'Package Cloud API Token'
    required: false
  publish_to_repository:
    description: 'Package Cloud repository to publish to (dev|test)'
    required: false
    default: ''
#outputs:
#  time: # id of output
#    description: 'time of docker start'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
  env:
    PACKAGECLOUD_TOKEN: '${{ inputs.packagecloud_token }}'
    PUBLISH_TO_REPOSITORY: '${{ inputs.publish_to_repository }}'

