# action.yml
# See
# https://help.github.com/en/actions/building-actions/creating-a-docker-container-action

name: 'LINZ Debian Packaging'
description: 'Build Debian packages for LINZ software repository'
inputs:
  release:
    description: Base Ubuntu Docker image version to build within, for example '20.04' or 'hirsute'
    required: true
  packages:
    description: Extra packages required to build this package
    required: false
    default: ''
  packagecloud_token:
    description: 'Package Cloud API Token'
    required: false
  packagecloud_repository:
    description: 'Package Cloud repository to publish to (dev|test)'
    required: false
    default: ''
  push_to_git_remote:
    description:
      'Name or URL of git remote to push changes to. If unset will be determined from containment of
      HEAD ref.'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.release }}
    - ${{ inputs.packages }}
  env:
    PACKAGECLOUD_TOKEN: '${{ inputs.packagecloud_token }}'
    PACKAGECLOUD_REPOSITORY: '${{ inputs.packagecloud_repository }}'
    PUSH_TO_GIT_REMOTE: '${{ inputs.push_to_git_remote }}'
