name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master
  schedule:
    - cron: '0 12 * * 0'

jobs:
  test:
    name: Test image building
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.4.0
      - run: make DISTRIBUTION=bionic image
