name: CI

on:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches:
      - master

jobs:
  test:
    name: Test image building
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.4.0
    - run: make DISTRIBUTION=bionic image
