name: CI

on: [push, pull_request]

jobs:

  test:
    name: Test image building on ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - ubuntu-18.04
          - ubuntu-20.04
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v1
    - run: make DISTRIBUTION=bionic image
