name: CI

on:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches:
      - master

jobs:

  test:
    name: Test image building
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Build default image (bionic)
      run: make image
    - name: Build trusty image
      run: DISTRIBUTION=trusty make image
