name: Test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master
  schedule:
    - cron: '0 12 * * 0'

jobs:
  test:
    name: Build ${{ matrix.distro }} on ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        distro:
          - 18.04
          - 20.04
          - 22.04
        runner:
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2.4.0

      - name: Install Nix
        uses: cachix/install-nix-action@v16

      - name: Build image
        run: nix-shell --pure --run 'make DISTRIBUTION=${{ matrix.distro }} image'
